usr/src/uts/common/io/sata/adapters/ahci/ahci.c
The original fix for OS-7672 is incompatible with what went into illumos as 10055, so revert it.
=> OS-8037 ahci_em_suspend() incorrectly VERIFY()s mutex_owned()

usr/src/pkg/manifests/system-test-smartostest.mf
This will still fail in the results until "make_test" itself is fixed upstream, hopefully soon.
=> OS-8049 make_test requires /usr/bin/make

usr/src/cmd/dladm/dladm.c
This is an incorrect invocation of the command, but if the encapsulation and vid are provided without the search plugin, then it crashes due to checking the encaps field twice instead of once for encaps and once for search.
```
zsh: segmentation fault (core dumped)  dladm create-overlay -e vxlan -v 23 overlay0
```
=> dladm create-overlay crashes if search plugin is not provided

usr/src/cmd/bhyve/block_if.c
This fixes the gcc4 compiler warnings (but still compiles fine with gcc7)
=> OS-8136 Add DISCARD/TRIM support to bhyve (fix compiler warning)

usr/src/cmd/nsadmin/bash/bash_completion.d/zone_alias
Change-Id: I5aa29572a26fe220d3ec75e3382fb66d19c8202f
I tested this by hot patching the zone_alias file and `exec`ing bash, then trying alias completion.
=> OS-8190 zone_alias bash completion stomps all over shell variables that we happen to use all the time

usr/src/uts/common/brand/lx/io/lx_netlink.c
This fixes "random" lx zone boot hangs.
Write-up at https://github.com/omniosorg/illumos-omnios/issues/798
=> LX: netlink errors have spurious flags

usr/src/uts/common/brand/lx/io/lx_netlink.c
See https://github.com/omniosorg/illumos-omnios/issues/794 for analysis and details for this.
Basically, OS-8181 got `getsockopt(SO_PROTOCOL)` working on netlink sockets, which enabled `systemd` to get further and trigger an assertion failure.
=> OS-8181 exposed fault in lx netlink bind/sendto

usr/src/lib/brand/lx/lx_brand/common/signal.c, usr/src/uts/common/brand/lx/os/lx_brand.c
I've been tracking down an intermittent problem with running Zimbra in lx zones since early 2018. It manifests with Zimbra in one of two ways and has been reported on both OmniOS and SmartOS.
1. A _defunct_ child of sudo, with sudo consuming significant CPU time.
```
19253  zsched
19416  systemd
19808  /opt/zimbra/common/lib/jvm/java/bin/java -XX:ErrorFile=/opt/zimbra/l
19947  /bin/bash /opt/zimbra/bin/postconf -X policy_time_limit
19950  sudo /opt/zimbra/common/sbin/postconf -X policy_time_limit
19952  <defunct>
```
2. A _defunct_ child of java, with java consuming significant CPU time.
```
27181  /opt/zimbra/common/lib/jvm/java/bin/java -XX:ErrorFile=/opt/zimbra/log -client
27309  <defunct>
```
By significant, the increased CPU activity is enough to make one of the reporting users …
=> LX: serialise parallel vfork()/clone(LX_CLONE_VFORK) invocations

usr/src/uts/common/brand/lx/syscall/lx_socket.c
https://www.illumos.org/issues/13175 recently added support for IP_RECVTOS to gate, and gate already has support for IPV6_RECVTCLASS. These should be wired up for LX.
Fixes #330 
```
[root@lx ~]# cat /etc/motd
__        .                   .
_|  |_      | .-. .  . .-. :--. |-
|_    _|     ;|   ||  |(.-' |  | |
|__|   `--'  `-' `;-| `-' '  ' `-'
/  ;  Instance (CentOS 7.4 20180323)
`-'   https://docs.joyent.com/images/container-native-linux
[root@lx ~]# yum install bind
...
[root@lx ~]# systemctl start named
[root@lx ~]# ps -ef | grep named
root      5549  5288  0 10:13 pts/2    00:00:00 grep --color=auto named
named     5529     1  0 10:13 ?        00:00:00 /usr/sbin/named -u named -c /etc/named.conf
[root@lx ~]# cat /var/named/data/named.run
managed-keys-zone: loaded serial 0
zone …
```
=> Wire up IP_RECVTOS and IPV6_RECVTCLASS in lx

usr/src/lib/fm/topo/modules/common/ipmi/ipmi_enum.c
This is Robert's fix.  I'm shepherding it.
=> OS-8251 libtopo plugins have uninitialized variables

usr/src/uts/common/brand/lx/procfs/lx_proc.h, usr/src/uts/common/brand/lx/procfs/lx_prvnops.c, usr/src/uts/common/brand/lx/sys/lx_brand.h
/proc/sys/kernel/random/uuid generates a random UUID on each read and is used by software such as xapian.
=> OS-8280 Add /proc/sys/kernel/random/uuid to LX brands

usr/src/uts/common/fs/proc/prvnops.c
=> OS-8389 Mismerged procfs collides PR_ARGV and PR_SECFLAGS

usr/src/Makefile.master, usr/src/uts/common/os/logsubr.c
In conjunction with TritonDataCenter/smartos-live#1069 which sets BANNER_YEAR, we now issue a two-line boot banner:
```
SmartOS Version joyent_20230109T215257Z 64-bit
Copyright 2022-2023 MNX Cloud, Inc.
```
This uses features from https://www.illumos.org/issues/12517
=> OS-8433 Welcome 2023

manifest
Inspired by tomorrow's merging I've not yet done.
There's ANOTHER possible bug near libzfs_core, but I'm asking RM the history behind it.  (I suspect you weren't this deep in illumos @bahamat at the time.)
=> OS-8447 Fix 3-digit permissions in manifest

usr/src/cmd/svc/milestone/smartdc-config
Companion: TritonDataCenter/smartos-live#1077
Change-Id: I2c8a81e269dd0c2dd2969669185309bd1c52907f
=> OS-8484 Headnode NTP config should be able to support RAN networks

usr/src/test/smartos-test/smartos-test.sh
This is set to draft because`smartos-test-tools` is a pkgsrc WIP right now. (FTR I'm in no hurry...)
=> OS-8505 Use new pkgsrc smartos-test-tools in smartos-test

usr/src/uts/common/fs/zfs/dmu.c
This has been tested, see https://illumos.org/issues/16087
=> 16087 import OpenZFS 15571 check dnode and its data for dirtiness (early pull)

usr/src/lib/libsmartsshd/common/mapfile-vers, usr/src/lib/libsmartsshd/common/sshd-plugin.c
Remove the per-key-type symbols for checking SSH keys as only the `sshd_user_key_allowed` function is used to check keys now. This PR is related to TritonDataCenter/illumos-extra/pull/101 but it is not essential, just cleanup.
See [OS-8502](https://mnx.atlassian.net/browse/OS-8502?focusedCommentId=123016) for testing notes.
[OS-8502]: https://mnx.atlassian.net/browse/OS-8502?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OS-8502 Remove unused symbols from libsmartsshd

usr/src/uts/common/brand/lx/syscall/lx_socket.c
Discovered by @smokris --> this patch improves the insufficient checking.
=> OS-8553 LX TCP_INFO socket option needs to be more strict

usr/src/test/smartos-test/smartos-test.sh
zfstests need to access /dev/zut.
Once present:
ztest@smartos:~$ /opt/zfs-tests/bin/zfstest -T casenorm                         
Test: /opt/zfs-tests/tests/functional/casenorm/setup (run as root) [00:00] [PASS]
Test: /opt/zfs-tests/tests/functional/casenorm/case_all_values (run as root) [00:01] [PASS]
Test: /opt/zfs-tests/tests/functional/casenorm/norm_all_values (run as root) [00:02] [PASS]
Test: /opt/zfs-tests/tests/functional/casenorm/sensitive_none_lookup (run as root) [00:01] [PASS]
Test: /opt/zfs-tests/tests/functional/casenorm/sensitive_none_delete (run as root) [00:00] [PASS]
Test: /opt/zfs-tests/tests/functional/casenorm/sensitive_formd_lookup (run as root) [00:00] [PASS]
Test: /opt/zfs-tests/tests/functional/casenorm/sensitive_formd_delete (run as root) [00:01] [PASS]
Test: …
=> OS-8565 zut is not loaded for zfs tests

usr/src/uts/i86pc/dboot/dboot_startkern.c
Missed to add MNX copyright line.
Also while there, make sure we only do output RICHMOND-16 workaround information once.
=> Add MNX Copyright in dboot_startkern.c

usr/src/test/util-tests/runfiles/default.run
Just removing it from `default.run`, unless you think it's worth killing with fire.
ALSO OF NOTE:  The bug report mentions that maybe we should not ship SVR4-adjacent items.  That's a harder test and beyond the scope of this bug.  It WOULD shrink the PI a bit if we did THAT, but that's not a problem for here.
=> OS-8572 Remove svr4pkg_test from SmartOS tests

usr/src/uts/common/ipp/ippctl.c, usr/src/uts/i86pc/dboot/dboot_printf.h, usr/src/uts/intel/io/dktp/hba/ghd/ghd_debug.h, usr/src/uts/intel/sys/promif.h, usr/src/uts/sun/sys/dada/adapters/ghd/ghd_debug.h, usr/src/uts/sun/sys/promif.h
in uts tree, replace __PRINTFLIKE with __KPRINTFLIKE. This is now possible because we have updated gcc 10. I guess, the actual integration will have to wait till we stop using gcc 7 as shadow.
=> OS-8606 uts should use KPRINTFLIKE

usr/src/uts/common/brand/lx/procfs/lx_proc.h, usr/src/uts/common/brand/lx/procfs/lx_prvnops.c
Some programs, such as steamcmd, expect these procfs entries to exist. The default value for both entries is hardcoded to 65534, unlike Linux, where it is a sysctl tunable. However, this should be 'good enough' for emulation purposes.
References : 
https://www.kernel.org/doc/html/latest/admin-guide/sysctl/fs.html#overflowgid-overflowuid
Create a lx branded zone instance and read the newly created entries.
```
[Connected to zone 'ca47b8b6-5bde-466a-b5ff-6ddb472d15b2' pts/5]
Welcome to Ubuntu 20.04.6 LTS (GNU/Linux 5.10.0 x86_64)
* Documentation:  https://help.ubuntu.com
* Management:     https://landscape.canonical.com
* Support:        https://ubuntu.com/pro
*--+--*--*
|\ |\ |\ |\
| \| \| \| \     #####  ####   #  #####  ###   #   # TM
+--*--+--*--*      #    #   #  #    #   #   #  ##  # …
```
=> OS-8628 LX: Add overflowuid and overflowgid to procfs

usr/src/test/smartos-test/smartos-test.sh
I am NOT respinning the whole build for this, but I *am* going to replace tests-tar and md5sum on appropriate manta directories.
=> OS-8662 smartos-test script needs to account for OS-8655
