usr/src/uts/i86pc/io/viona/viona_rx.c
=> OS-8027 reinstate mac-loopback hardware emulation on Tx [fix debug]

usr/src/man/man9f/ddi_ffs.9f
The change and fix are fairly straighforward and obvious.
=> OS-8082 Typo in ddi_ffs(9F)

usr/src/cmd/fs.d/nfs/mountd/mountd.c, usr/src/cmd/fs.d/nfs/nfsd/nfsd.c, usr/src/cmd/fs.d/nfs/svc/nfs-server, usr/src/lib/brand/joyent-minimal/zone/platform.xml, usr/src/lib/brand/joyent/zone/manifests, usr/src/lib/brand/joyent/zone/platform.xml, usr/src/uts/common/fs/nfs/nfs_auth.c, usr/src/uts/common/fs/nfs/nfs_sys.c, usr/src/uts/common/klm/nlm_impl.h, usr/src/uts/common/sys/zone.h
Three commits from the illumos-joyent nfs-zone branch that need to be here, plus various cleanups from the nfs-zone work.  NOTE:  No copyrights were removed, but they were either duplicate suppression, or in one case, a move of one to a block created by the Nexenta nfs-zone work.
=> nfs-zone merge cleanup

manifest, usr/src/lib/brand/lx/zone/Makefile, usr/src/lib/brand/lx/zone/lx_boot.ksh, usr/src/lib/brand/lx/zone/lx_boot_zone_void.ksh
=> OS-8156 lx void linux image support

usr/src/uts/common/brand/lx/syscall/lx_ioctl.c
Work by @oetiker
This is integrated into OmniOS and has solved problems with systemd in the omnios ubuntu 20.04 image
Tobi's notes:
* a service tries to start a process NOT as root by setting the User property in the [Service] section
* systemd will fail horribly complaining about Failed to change ownership of terminal
* what terminal ??? you will ask.
* a look at https://fossies.org/linux/systemd/src/core/execute.c and the chown_terminal function shows that systemd want's to play it safe and will chown the tty the process is connected to before running anything
* Looking at the configuration of systemd https://www.freedesktop.org/software/systemd/man/systemd.exec.html we further learn that StandardInput is set to 'null' by default causing it to be connected to /dev/null ... which I think …
=> isatty() should return ENOTTY if not a TTY

usr/src/lib/brand/lx/lx_brand/common/sendfile.c
=> joyent/illumos-joyent#326 LX sendfile returns EINVAL at EOF when it should return 0

usr/src/cmd/svc/milestone/net-early-admin
This patch has been running on all of our `mlxcx` equipped compute nodes for a few months.
=> joyent/illumos-joyent#345 early-admin sets MTU on aggr without setting MTU on underlying NICs

usr/src/uts/common/exec/java/java.c, usr/src/uts/common/exec/shbin/shbin.c
Reviewed by: Dan McDonald <danmcd@joyent.com>
=> OS-8258 OS-4119 forgot about java and shbin exec types

usr/src/uts/common/brand/lx/os/lx_misc.c, usr/src/uts/common/disp/thread.c, usr/src/uts/common/fs/zfs/spa_misc.c, usr/src/uts/common/os/kcpc.c, usr/src/uts/common/os/schedctl.c, usr/src/uts/common/sys/proc.h, usr/src/uts/i86pc/io/vmm/vmm.c, usr/src/uts/intel/ia32/os/cpc_subr.c, usr/src/uts/intel/ia32/os/fpu.c, usr/src/uts/intel/ia32/os/sundep.c, usr/src/uts/intel/ia32/os/sysi86.c, usr/src/uts/sun4u/os/cpc_subr.c, usr/src/uts/sun4v/os/cpc_subr.c
Portions contributed by: Jerry Jelinek <gjelinek@gmail.com>
=> OS-8288 Pull in 13902 and 13915 early

usr/src/uts/common/fs/zfs/dmu.c, usr/src/uts/common/fs/zfs/sa.c, usr/src/uts/common/fs/zfs/sys/spa_impl.h, usr/src/uts/common/fs/zfs/zfs_dir.c, usr/src/uts/common/fs/zfs/zfs_vfsops.c, usr/src/uts/common/fs/zfs/zio.c
Tested by disassembly-and-diff, see bug report.
=> OS-8293 Remove ZFS whitespace & comment diffs to reduce upstream diff noise

usr/src/cmd/varpd/varpd.c, usr/src/cmd/zoneadmd/zfd.c, usr/src/cmd/zoneadmd/zoneadmd.c, usr/src/lib/varpd/libvarpd/common/libvarpd.h, usr/src/lib/varpd/libvarpd/common/libvarpd_overlay.c, usr/src/uts/common/io/zfd.c
Needed changes to let gcc10 build illumos-joyent as a shadow compiler.  A step towards full-blown gcc10 compilation.
=> OS-8322 Prep illumos-joyent for gcc10

usr/src/lib/brand/lx/lx_brand/sys/lx_mount.h
=> OS-8338 lx_nfs structures declare variables

usr/src/uts/common/os/logsubr.c
Change-Id: I350d1c80716a4cd1d7be748d1425ce05298a46e4
=> OS-8345 Welcome 2022

usr/src/cmd/svc/milestone/mdata-fetch
Change-Id: I28b58cdb4092b268a2284bd896be8e7aac3e9710
=> OS-8346 mdata:fetch clobbers IPv6 addresses if they have caps

manifest
Already tested, per the bug report.
=> OS-8350 OS-3792 forced hardlink to a symlink

usr/src/uts/common/brand/lx/syscall/lx_prctl.c
I haven't been able to test this change yet[^1], but before I spend much more time on it, I wanted to check whether the illumos-joyent maintainers would be open to addressing #383 by incorporating an approach like this.
[^1]: (I'm new to Illumos system development, and am currently struggling with getting the system to build, regardless of this change.)
=> OS-8352 Fake out Linux's SECCOMP to allow elasticsearch8 to run in LX zones

usr/src/Makefile.testarchive
Overlooked since November, we REALLY need to fix this.
=> OS-8360 We forgot about illumos 14220 in Makefile.testarchive

usr/src/uts/common/brand/lx/cgroups/cgrps_node.c, usr/src/uts/common/brand/lx/devfs/lxd_node.c, usr/src/uts/common/brand/lx/devfs/lxd_vnops.c, usr/src/uts/common/fs/hyprlofs/hyprlofs_dir.c, usr/src/uts/common/fs/hyprlofs/hyprlofs_vfsops.c, usr/src/uts/common/fs/tmpfs/tmp_dir.c, usr/src/uts/common/fs/tmpfs/tmp_vfsops.c, usr/src/uts/common/fs/tmpfs/tmp_vnops.c, usr/src/uts/common/inet/tcp/tcp_bind.c, usr/src/uts/common/io/vnd/vnd.c
Our portion of accepting syntactic sugar.
=> OS-8359 Cleanup (KM_NOSLEEP | KM_NORMALPRI) in illumos-joyent

usr/src/lib/brand/lx/lx_vdso/tools/vdso_tool.c
=> OS-8372 Bring in OmniOS fix for lx_vdso.so

Jenkinsfile
Change-Id: If6f8f882a6abcf00e75dadac8acf79b2884b1e6e
=> TOOLS-2542 SmartOS project repos need Jenkinsfile update

usr/src/lib/varpd/svp/common/libvarpd_svp.c
Change-Id: Ic764a5f33423908ee89af7f4aa1925ecf8c90396
=> OS-8407 varpd/svp multicast confusion

usr/src/lib/brand/joyent-minimal/zone/manifests
Change-Id: I08bdf17cd398468bd9e0c3b38551f0be0dc2bef5
=> OS-5054 joyent-minimal should import ndp by default

usr/src/test/smartos-test/smartos-test.sh
Testing notes already in ticket.
=> OS-8435 Let smartos-test put /etc/shadow on /etc itself

usr/src/pkg/manifests/system-test-ostest.p5m, usr/src/test/os-tests/runfiles/default.run, usr/src/test/os-tests/tests/signalfd/Makefile, usr/src/test/os-tests/tests/signalfd/multipoll.c, usr/src/uts/common/io/signalfd.c
15386 signalfd overzealous with clean-up
Reviewed by: Dan McDonald <danmcd@mnx.io>
Reviewed by: Bill Sommerfeld <sommerfeld@alum.mit.edu>
=> OS-8444 Backport illumos#15386 to release-20230209

usr/src/cmd/fs.d/nfs/clear_locks/clear_locks.c, usr/src/uts/common/fs/nfs/nfs4_state.c, usr/src/uts/common/fs/nfs/nfs_sys.c, usr/src/uts/common/nfs/nfssys.h, usr/src/uts/intel/ml/modstubs.s
xxxxx clear_locks(8) needs resilience
Reviewed by: Richard Lowe <richlowe@richlowe.net>
=> Bring in clear_locks fix to release-20230209

usr/src/test/smartos-test/README
A side-effect of this is to add a whole subsection on how we use smartos-test on every release.  I might include a shippable report.sh script.
=> OS-8457 Update smartos-test's README

manifest
=> OS-8448 libzfs_core.so.1 is in /usr/lib, symlink is in /lib, unlike -gate

usr/src/boot/forth/menu.4th
Discovered via mailing list complaints about network/physical failing.
=> OS-8466 piadm(8) PI menu leaves garbage in bootparams(5)

usr/src/lib/brand/lx/zone/lx_boot_zone_busybox.ksh
Change-Id: I311fcfaa30ab1c125c392c5292af4cda4a6135cb
=> OS-8476 lx_boot_zone_busybox corrupts /etc/init.d/networking

usr/src/common/brand/lx/lx_auxv.c
Change-Id: Ia6abaf76848006dbece4fe2fcf011d8ba415237f
=> OS-8480 LX should always set AT_SECURE one way or the other for root

manifest
Good catch by @rmustacc and @jperkin about me missing a manifest entry from August.
=> OS-8494 Merge of illumos#15736 missed manifest

usr/src/boot/Makefile.version, usr/src/boot/common/tem.c, usr/src/boot/sys/sys/tem_impl.h, usr/src/data/terminfo/termcap.src, usr/src/data/terminfo/terminfo.src, usr/src/uts/common/io/tem.c, usr/src/uts/common/io/tem_safe.c, usr/src/uts/common/sys/tem_impl.h
Reviewed by Dan McDonald <danmcd@mnx.io>
Reviewed by Brian Bennett <brian.bennett@mnx.io>
Approved by Dan McDonald <danmcd@mnx.io>
=> OS-8511 curl progress bar is too wide on wscons (early port of illumos#14919)

usr/src/man/man8/altexec.8
Change-Id: I548adb0203a335e097ef00315e3f5620405514a9
=> OS-8548 Typo in altexec(8) man page

usr/src/cmd/bhyve/uart_emul.c
Details are in the ticket. I will do further testing of this, for now just looking for initial review.
=> OS-8556 bhyve uart is too fast

usr/src/man/man8/altexec.8
Change-Id: I348e20c2f0e96faf8a1e46959fc02c9085370eb5
=> OS-8614 altexec man page shows incorrect path

usr/src/uts/common/os/logsubr.c
Change-Id: I5481e3459f503957570e67c039fa268c0b08e274
=> OS-8613 Welcome 2025

usr/src/cmd/svc/milestone/fs-joyent
https://smartos.org/bugview/OS-8644
=> OS-8644: Keep swap data blocks out of ARC

usr/src/lib/brand/bhyve/zone/boot.c, usr/src/lib/brand/bhyve/zone/statechange
I guess @cneira and I are the coauthors of this.
=> OS-6892: viona should allow promisc interfaces
